name: cmake-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  IDA_VERSION_FOR_ARTIFACT_NAME: "9.3"
  IDASDK_REF: v9.3.0-release

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: google/bindiff
        ref: 1c908013e111ca9a36a3e0a182bab13f963f9658
        path: bindiff

    - uses: actions/checkout@v4
      with:
        repository: google/binexport
        ref: bdb8c4430549e69d4a9a7531c59b197f3a0757e6
        path: binexport

    - name: Apply patch
      shell: bash
      run: |
        cd binexport
        git apply ../patches/binexport-bdb8c4430549e69d4a9a7531c59b197f3a0757e6.patch

    - name: Install ninja-build tool
      uses: aseprite/get-ninja@main

    - uses: actions/checkout@v4
      with:
        repository: HexRaysSA/ida-sdk
        ref: ${{ env.IDASDK_REF }}
        path: idasdk93

    - name: Configure CMake
      shell: bash
      run: |
        cmake -S bindiff -B build/out -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          -DCMAKE_INSTALL_PREFIX=build/out \
          -DBINDIFF_BINEXPORT_DIR=binexport \
          "-DIdaSdk_ROOT_DIR=${PWD}/idasdk93/src" \
          -DBoost_INCLUDE_DIR="${PWD}/binexport/boost_parts" \
          -DBoost_LIBRARY_DIRS="${PWD}/binexport/boost_parts"

    - name: Build
      working-directory: build/out
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test
      working-directory: build/out
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BinDiff-IDA-${{ env.IDA_VERSION_FOR_ARTIFACT_NAME }}-macos-26
        path: |
          build/out/bindiff
          build/out/bindiff.exe
          build/out/ida/bindiff*
          build/out/tools/bindiff*

    - name: Configure CMake (binexport)
      shell: bash
      run: |
        cmake -S binexport -B build/out/_deps/binexport-build -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          -DCMAKE_INSTALL_PREFIX=build/out/_deps/binexport-build \
          -DBINEXPORT_ENABLE_IDAPRO=ON \
          -DBINEXPORT_ENABLE_BINARYNINJA=ON \
          "-DIdaSdk_ROOT_DIR=${PWD}/idasdk93/src" \
          -DBoost_INCLUDE_DIR="${PWD}/binexport/boost_parts" \
          -DBoost_LIBRARY_DIRS="${PWD}/binexport/boost_parts"

    - name: Build (binexport)
      working-directory: build/out/_deps/binexport-build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test (binexport)
      working-directory: build/out/_deps/binexport-build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts (binexport)
      uses: actions/upload-artifact@v4
      with:
        name: BinExport-IDA-${{ env.IDA_VERSION_FOR_ARTIFACT_NAME }}-macos-26
        path: |
          build/out/_deps/binexport-build/binaryninja/binexport*
          build/out/_deps/binexport-build/ida/binexport*
          build/out/_deps/binexport-build/tools/binexport2dump*
